version: "3"
services:
  directus:
    image: directus/directus:11.1.2
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: "replace-with-secure-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "http://localhost:4200"
      AUTH_DISABLE_DEFAULT: "false"
      AUTH_TOKEN_EXPIRATION: "24h" 
      AUTH_REFRESH_TOKEN_EXPIRATION: "7d"